trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  cheminAPI: '**/src/Sec.Market.API/*.csproj'
  cheminMVC: '**/src/Sec.Market.MVC/*.csproj'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      $(cheminAPI)
      $(cheminMVC)
    feedsToUse: 'select'
  displayName: 'Restaurer les packages NuGet'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      $(cheminAPI)
      $(cheminMVC)
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Génération de la solution'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'list'
    arguments: 'package --vulnerable --include-transitive'
    projects: |
      $(cheminAPI)
      $(cheminMVC)
  displayName: 'Analyse des vulnérabilités avec DotNet CLI'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publication du package dans Azure DevOps'
